services:
  - type: web
    name: webrtc-signaling-server
    env: node
    region: oregon
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
